### ISSUE TITLE
I'm getting errors running this

### ISSUE THREAD

**Issue by alex-w-k** [mjabali/astolfo#2]
I got:
```
/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'success' of undefined
    at Client.<anonymous> (/Users/alex/3module/authy-testing-sample/app.js:274:20)
    at Client.tryCatcher (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alex/3module/authy-testing-sample/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
and then when I check on twilio it shows that I was sent back a `Success!` message.
Not sure what to do from here.

**Comment by mjabali** [comment]
The 'Success!' message you see in the Twilio Console is probably coming from the response of the /verification webhook. Are you able to see the phone verification message body in the Twilio Console (i.e. Your <app> verification code is: XXXX)? Have you cloned the repo recently? What's the version of the authy-client you have in the package.json? I remember seeing some issues with that library before throwing similar error messages.

**Comment by mjabali** [comment]
No further activity. Forked into https://github.com/AuthySE/authy-testing-sample
